Added Git workflowv3

diff --git a/.github/workflows/CI_Test.yml b/.github/workflows/CI_Test.yml
--- a/.github/workflows/CI_Test.yml
+++ b/.github/workflows/CI_Test.yml
@@ -4,7 +4,7 @@ on:
   pull_request:
     branches:
       - main
-  
+
 jobs:
   build:
     runs-on: ubuntu-latest
@@ -16,7 +16,5 @@ jobs:
         with:
           node-version: '14'
       - name: Install dependencies
-        run: npm install
-      - name: Exit with status code 0
-        run: exit 0
-        # Use `exit 1` to simulate a failure in the workflow.
+        run: npm install && exit 0 || exit 1 
+        # If npm install is successful, then it will exit 0, otherwise failure leads to exit 1
